import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const roboto = Roboto({
  weight: ['400', '500', '700'], // Choose weights you need
  subsets: ['latin'],
  variable: '--font-roboto', // Optional, useful for Tailwind
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Omkkar Innovations",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.variable}>
      <body
        className="font-roboto bg-gray-50"
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
